### ISSUE TITLE
Access data without having to write to disk

### ISSUE THREAD

**Issue by HackerDaGreat57** [end2endzone/bin2cpp#57]
This is the way I did it:

```
//Datafile loading
const bin2cpp::File& d_suitcaseGeneral = bin2cpp::getD_suitcaseGeneralFile();
bool s_suitcaseGeneral = d_suitcaseGeneral.save("suitcaseGeneral.bmp");

HBITMAP img_suitcaseGeneral = (HBITMAP)LoadImage(NULL, _T("suitcaseGeneral.bmp"), IMAGE_BITMAP, 96, 70, LR_LOADFROMFILE);
```

Is there a way to access the data without writing it to disk? For example I could use win32's `CreateBitmap` func and reshape my code to look like this:

```
//Datafile loading
const bin2cpp::File& d_suitcaseGeneral = bin2cpp::getD_suitcaseGeneralFile();
bool d_suitcaseGeneral.load("TheInternalFileName");

HBITMAP img_suitcaseGeneral = (HBITMAP)LoadImage(NULL, _T("TheInternalFileName"), IMAGE_BITMAP, 96, 70, LR_LOADFROMFILE);
```

The reason I want to do this is because I want my app to be **completely** portable - No install, no DLLs, no .iso file, just the one exe. Win64 resources are not an option. I added my app's entire source file in case you want more reference.

[main.zip](https://github.com/end2endzone/bin2cpp/files/7192993/main.zip)

**Comment by end2endzone** [comment]
Yes, bin2cpp provides ways to get access to the binary data without having to write to the disk.

Take a look at the [Code Sample](https://github.com/end2endzone/bin2cpp#code-sample-querying-the-generated-code) in the README.md document. The binary data is loaded into ram on first use. Based on the README example, the data is loaded into ram when calling `bin2cpp::getHelloWorldHtmlFile()`. You can get access to the binary array by calling `const char * buffer = resource.getBuffer();`. The length of the binary array can be retrieved with `size_t bufferSize = resource.getSize();`.

A quick google search returns multiple results on how to create an HBITMAP from a byte array. You should use fonction [CreateDIBitmap](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createdibitmap) instead of `LoadImage()`. I think what you are looking for is [this example](https://stackoverflow.com/questions/4993518/arraybyte-to-hbitmap-or-cbitmap) from StackOverflow. Instead of `bytes`, use `buffer` from the README example.

I don't know why using [Windows Resources](https://en.wikipedia.org/wiki/Resource_(Windows)) is not an option for a use case such as yours but bin2cpp can also be used with _Windows Resources_. It provides the same interface (like [this one](https://github.com/end2endzone/bin2cpp#output-file-generated_helloworldh)) to the main application which means you can get the original filename, file size and stuff like that.

**Comment by HackerDaGreat57** [comment]
Thanks for the comment. Will try to implement.
